version: '2.1'

services:  
  nodeBase:
    container_name: node
    image: node:11-slim
    volumes:
      - ./:/var/www/html
      - nodemodules:/var/www/html/node_modules
      - ${PWD}/.env.example:/var/www/html/.env
      - ${PWD}/.git:/var/www/html/.git
    working_dir: /var/www/html
  install:
    extends:
      service: nodeBase
    command: npm install 
  watch:
    extends:
      service: nodeBase
    command: npm run watch
  test:
    extends:
      service: nodeBase
    command: npm run test
  tdd:
    extends:
      service: nodeBase
    command: npm run tdd
  codecov:
    extends:
      service: nodeBase
    command: npm run codecov

volumes:
  nodemodules:
    external: true