version: '2.1'

services:
  app:
    container_name: app
    build:
      context: ./
      dockerfile: ./dockerfiles/app.dockerfile
    volumes:
      - ./:/var/www/html
    environment:
      - 'DB_PORT=3306'
      - 'DB_HOST=database'
    networks:
      backend:

  web:
    build:
      context: ./
      dockerfile: ./dockerfiles/web.dockerfile
    volumes_from:
      - app
    ports:
      - 8080:80
    networks:
      backend:
        aliases:
          - api.dev

  database:
    container_name: database
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - 'MYSQL_DATABASE=homestead'
      - 'MYSQL_USER=homestead'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=secret'
    ports:
      - 33061:3306
    networks:
      backend:
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          '-uhomestead',
          '-psecret',
          'ping',
          '-h',
          'database',
        ]
      timeout: 20s
      retries: 10

  node:
    container_name: node
    image: node:11-slim
    volumes_from:
      - app
    volumes:
      - nodemodules:/var/www/html/node_modules
    working_dir: /var/www/html
    command: npm run watch

volumes:
  nodemodules:
    external: true
  dbdata:

networks:
  backend:
    driver: bridge
